### ISSUE TITLE
Failed to parse plugin "homebridge-tasmota-control"

### ISSUE THREAD

**Issue by fkroepfl** [grzegorz914/homebridge-tasmota-control#10]
Since latest update there is the following error:

`[05/02/2024, 09:25:24] [Homebridge UI] Failed to parse plugin "homebridge-tasmota-control": /var/lib/homebridge/node_modules/homebridge-tasmota-control/package.json: Unexpected end of JSON input
`

**Comment by grzegorz914** [comment]
try 0.10.3-beta.0 and let me know

**Comment by fkroepfl** [comment]
FYI: Seems to be working again, although only after a few restarts.

`[05/02/2024, 12:13:32] [homebridge-tasmota-control] Loaded homebridge-tasmota-control v0.10.3 child bridge successfully`
