### ISSUE TITLE
Tasmota Smartplugs freeze with newest Plugin

### ISSUE THREAD

**Issue by sjung87** [grzegorz914/homebridge-tasmota-control#14]
Hi grzegorz914,
first, thanks for the great Homebridge Plugin :)
I recently recognized a freeze of my smartplugs running Tasmota after upgrading to the latest v0.10.31 plugin version.
So the plugs are not responding anymore - meaning the web interface is not loading, the buttons on the device is not working, etc. But they are connecting to Wifi. Restarts and Resets are not working. Only after disabling the Homebridge Plugin, the device are working just as normal.
From the logs I can see that Homebridge is putting several pings to the devices per second. From what I see it is 25 per second and then 15s later the next 25.

Used plugin: v0.10.31
Tasmota version: 13.1

I don't know the version that I had before, but probably v0.10.20-somtehing (this was working fine)

Is this a know issue? Can I provide some more infos / logs?

Thanks and Best, Sebastian

**Comment by grzegorz914** [comment]
Can you post the debug log, go to plugin settings, advanced settings>>system>>debug, enable it and get the whole log.

**Comment by sjung87** [comment]
Thanks for the quick response. Will do that and post the logs here tomorrow.

**Comment by sjung87** [comment]
The logs seem normal from what I can see (no errors / warnings / timeouts).
The logs for the smartplug are every 5s the following:
(I attached the full log anyway)

```
[7/30/2024, 1:51:32 PM] [homebridge-tasmota-control] Device: 192.168.1.63 Smartplug-Babycam, debug: Requesting status.
[7/30/2024, 1:51:32 PM] [homebridge-tasmota-control] Device: 192.168.1.63 Smartplug-Babycam, debug: Power status: {
  "POWER": "OFF"
}
[7/30/2024, 1:51:32 PM] [homebridge-tasmota-control] Device: 192.168.1.63 Smartplug-Babycam, debug: Sensors status: {
  "Time": "2024-07-30T13:51:31",
  "ENERGY": {
    "TotalStartTime": "2023-10-28T20:42:01",
    "Total": 0.129,
    "Yesterday": 0.011,
    "Today": 0,
    "Power": 0,
    "ApparentPower": 0,
    "ReactivePower": 0,
    "Factor": 0,
    "Voltage": 0,
    "Current": 0
  }
}
```

I guess this is normal, right?

The first issues with the devices came up like 2-3 days after I installed the update for the plugin. So I will update the logs here when the device is frozen again.

[homebridge-tasmota-control.log.txt](https://github.com/user-attachments/files/16427272/homebridge-tasmota-control.log.txt)

**Comment by sjung87** [comment]
Now I feel totally stupid. The described behavior was occurring three times, and I was trying different ways to resolve it (uninstall plugin, reset Tasmota devices, etc.). Now that I opened the issue, all works as expected for a couple of days now. So I will close the issue. If in the future the devices will freezes again, I collect all the logs and would open a new one.
