### ISSUE TITLE
Tasmota Smartplugs freeze

### ISSUE THREAD

**Issue by sjung87** [grzegorz914/homebridge-tasmota-control#15]
Hi grzegorz914,
relating to https://github.com/grzegorz914/homebridge-tasmota-control/issues/14

Now the plugs froze again and I could get some (hopefully more useful) logs. Including a restart of the plugin (child bridge restart 4:26:09PM and 4:35:01 PM).
Here are the logs:
[homebridge-tasmota-control.log (2).txt](https://github.com/user-attachments/files/16588369/homebridge-tasmota-control.log.2.txt)

Used plugin: v0.10.32
Tasmota version: 14.1

Also two points I recognized:
- after restarting the child bridge, the plugs seems to "unfreeze" for some time
- strangely after one day the Module type within Tasmota are changing from "Sonoff Basic Plug (0)" to "Sonoff Basic (1)"; don't know if there is any relation.
→ After that change, the values in the webinterface are missing and the hardware button is no longer working - because Tasmota doesn't have the correct module / hardware config, so maybe it also can't send the requested values to the Homebridge plugin?
→ I have multiple plugs at home, only some are connected to Homebridge - and only those connected ones are showing this behavior. The others stay with their configuration.

Thanks for looking into this!
Best, Sebastian

**Comment by grzegorz914** [comment]
Should be fixed with this update
