### ISSUE TITLE
Tasmota sensor data is not updated

### ISSUE THREAD

**Issue by RalfOGit** [grzegorz914/homebridge-tasmota-control#16]
Good morning Grzegorz,

Thanks for providing this powerful tasmota bridge to github. It helps a lot to get a quick start to the homekit world. 

I was playing around with sensor data from a tasmota NOUS A1 plug. This plug provides sensor data below the standard StatusSNS node. I noticed that the homebridge-tasmota-control provides just the initial data and never updates the sensor readings.

When I changed the code in checkDeviceState() from: 
  const power = sensorsData.Power ?? false;
to
  const power = sensorsStatus.ENERGY.Power ?? false;
it works for me.

Unfortunately Homekit does not support electrical power measures out of the box. I mapped them to ambiant luminance to get them displayed in the Home App. This is a bit messy, therefore I hesitate to provide a pull-request with my full set of changes.

Best regards and enjoy the weekend
Ralf

**Comment by grzegorz914** [comment]
Yes, here is missing ENERGY key, but this is irrelevant because as You wrote the HomeKit doesn’t support Energy characteristics and this data is never used in my plugin. This is prepare for iOS 18.x where the energy will be added to HomeKit.

**Comment by grzegorz914** [comment]
In 0.11.1-beta the sensor update data should be fixed, try and let me know

**Comment by RalfOGit** [comment]
Thank you for the quick fix!!

**Comment by RalfOGit** [comment]
I just updated to your latest commit. Sensor readings are updated now. Thanks a lot.
