### ISSUE TITLE
Diable Log Info does not work

### ISSUE THREAD

**Issue by xatrix78** [grzegorz914/homebridge-tasmota-control#2]
Hi, 

thank you for this plugin! It´s very good!

When a Device is offline it appears in the Log, also when disable Log is activ:

 Device: 192.168.69.48 Beamer, Device Info eror: Error: connect EHOSTUNREACH 192.168.69.48:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.69.48',
  port: 80,
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, state: Offline, trying to reconnect

Thank you for bugfixing.

**Comment by grzegorz914** [comment]
This is log.error will always appear in the console.
