### ISSUE TITLE
Device power status is not correct

### ISSUE THREAD

**Issue by tpellegrini** [grzegorz914/homebridge-tasmota-control#4]
I have a few Sonoff S31 devices flashed to run Tasmota. They were running 11.0.0 and 11.1.0, but were updated to 12.0.2 to attempt to resolve this issue.

The devices are recognized by the plugin, but the status always shows as "Off." If I click the item in the Accessory list, the outlet turns on, however the state is not reflected in the Accessory list. If I click the item again the state does not change, i.e., the device does not power off.

From the status log + debugging I see these contradictory messages:

>>
[07/08/2022, 16:50:59] [tasmotaControl] Device: 192.168.2.25 Prusa i3 MK3S+ MMU, get state: OFF
[07/08/2022, 16:51:04] [tasmotaControl] Device: 192.168.2.25 Prusa i3 MK3S+ MMU, debug response: {
  "POWER1": "ON"
}
<<

Note that no events for the state change are logged, as indicate and expected. Perhaps the try block at 215 may not be being satisfied?

I have attached a log which I hope provides useful guidance: [tasmota_s31_debug.txt](https://github.com/grzegorz914/homebridge-tasmota-control/files/9277696/tasmota_s31_debug.txt)

I'm not sure what additional details you require. but please let me know how I can assist in resolving this. 

~ Tony

**Comment by grzegorz914** [comment]
Thanks, 
can you try 0.4.5-beta and let me know

**Comment by tpellegrini** [comment]
I installed the update but experienced no difference in behavior. I recreated the switches to make certain there wasn't something somehow amiss in the config file and also changed the plugin to run as a child bridge as recommended.

As above, clicking on the accessory in the list will turn the device on. The state is not reflected in the log (i.e. no "set state" log message as expected) nor is the UI updated with the correct state. As such, there is no ability to toggle the power off again.

Looking at it, I suspected the dependency to axios was not satisfied. My modules list did not list axios, so I attempted to install it but borked the install in the process ("added 8 packages, removed 1171 packages"). Doh! I haven't yet had a chance to reinstall homebridge,.

erhaps you could comment on whether I might have been on the right track? Should I not see axios in the modules list? (Sorry, I'm a bit out of my element here, but I am trying to learn.)

Thanks again!

**Comment by grzegorz914** [comment]
Please get the full log

**Comment by grzegorz914** [comment]
Please try also 0.4.6 beta

**Comment by tpellegrini** [comment]
Apologies for the delay. 

I was able to confirm that the latest beta 0.4.6 has resolved the issue. The accessory page now shows the proper state and controls the device as expected (on and off).

Thank you!
