### ISSUE TITLE
Is DewPoint a characteristic type supported by HomeKit?

### ISSUE THREAD

**Issue by fkroepfl** [grzegorz914/homebridge-tasmota-control#9]
Since a TH16 with the AM 2301 sensor also transmits the dew point, the question arises as to whether this can be shown or marked separately, because otherwise the standard displays of the Apple Home, e.g. in the climate overview, will get a little confused, because room temperature is one thing, the dew point is another.

How do you see this?

See also attached screenshot.

![image](https://github.com/grzegorz914/homebridge-tasmota-control/assets/6333880/a7916f5d-88c6-4879-a8d6-9d269a448734)

**Comment by grzegorz914** [comment]
Apple doesn’t support Dew Point Characteristic but is same as Temperature. In Your case You will se 2 sensors 1 - Temperatue, 2 - Dew Point. In this case you can use Dew Point and Temperature for scene or automations. If you se other possibility to present it in Home app let me know.
